version: '2'

services:
  bot:
    image: deril/jewish-bot:1.1
    restart: on-failure:10
    expose:
      - "5000"
    volumes:
      - ./database:/db

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    links:
      - bot
