version: '3.4'

networks:
  traefik-reverse-proxy:
    external:
      name: web

services:
  bot:
    image: ghcr.io/deril/jewish-bot-c:latest
    container_name: jewish-bot
    restart: on-failure:10
    networks:
      - traefik-reverse-proxy
    ports:
      - "5004:5000"
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.jewishbotc.rule=Host(`jewishbot.derilok.xyz`)
      - traefik.http.routers.jewishbotc.entrypoints=websecure
      - traefik.http.routers.jewishbotc.tls=true
      - traefik.http.routers.jewishbotc.tls.certresolver=cloudflare
      - traefik.http.services.jewishbotc.loadbalancer.server.port=5000
